// "Will AI actually help your business?" Pure data for the decision board and
// the reference guide beneath it. No imports, so the prerender can read it.
//
// STYLE: no em dashes; firm name in full. This is business and technology
// guidance, not financial product advice. Regulatory notes are general.

export const sectors = [
  {
    key: 'advice',
    label: 'Financial advice or AFSL holder',
    points: [
      'Anything that touches personal financial information sits under the Privacy Act and the licensee’s own data policies. Check with your licensee before a single client file goes into a public tool.',
      'Advice documents carry best-interests and record-keeping obligations. AI can draft, but an adviser signs off and the file must show they did.',
      'AI-generated marketing still has to meet financial product advertising rules. "The AI wrote it" is not a defence.',
      'Complaints handling needs a human owner and timeframes. Automation can triage, not resolve.',
    ],
    verdict: 'Strong fit for internal drafting and admin, only with an enterprise or private deployment and licensee approval.',
  },
  {
    key: 'health',
    label: 'Health or allied health',
    points: [
      'Health information is "sensitive information" under the Privacy Act, with stricter collection and use rules than ordinary personal data.',
      'Registered practitioners remain personally responsible for clinical decisions and records, however they were produced.',
      'AI scribes are becoming common but need patient consent, secure storage, and a clinician reviewing every note.',
    ],
    verdict: 'Good fit for note-taking and admin with a health-specific, Australian-hosted tool. Avoid general chat tools for anything identifying a patient.',
  },
  {
    key: 'legal',
    label: 'Legal or accounting',
    points: [
      'Client confidentiality and legal professional privilege can be put at risk by pasting material into a tool whose terms allow training on inputs.',
      'Tax agents and accountants carry professional obligations. Advice generated by a tool is still the agent’s advice.',
      'AI is prone to inventing citations, case names and section numbers. Anything that references law needs verification, every time.',
    ],
    verdict: 'Useful for research starting points, summaries and correspondence. Never the final word on anything with a section number in it.',
  },
  {
    key: 'retail',
    label: 'Retail, ecommerce or hospitality',
    points: [
      'Customer data is still personal information, and marketing automation must respect the Spam Act’s consent and unsubscribe rules.',
      'Never let a tool handle raw card details. Payment systems exist for that.',
      'AI-generated product claims and reviews are covered by Australian Consumer Law. Fake or misleading content is the business’s problem.',
    ],
    verdict: 'Lowest compliance friction of any sector. Product descriptions, customer replies and inventory forecasting are all sensible early uses.',
  },
  {
    key: 'trades',
    label: 'Trades, construction or professional services',
    points: [
      'Quotes and contracts generated with AI need the same care as any template. The tool does not know your margins, your insurer’s wording or the state’s building rules.',
      'Client and site data is generally low-sensitivity, so the main risk is accuracy rather than privacy.',
      'If you hold personal information on employees or subcontractors, ordinary Privacy Act rules apply.',
    ],
    verdict: 'Strong fit for quoting, scheduling and chasing invoices. Keep a human on anything with a dollar figure or a legal clause.',
  },
  {
    key: 'other',
    label: 'Something else',
    points: [
      'Using AI to screen candidates or assess performance can create discrimination risk if the criteria are opaque. Keep a person in the decision.',
      'Tell staff what tools are approved and what data must never go into them. Most breaches are a well-meaning employee pasting a client email into a free tool.',
      'Check whether the tool uses your inputs to train its models. Business and enterprise plans usually do not; free plans often do.',
    ],
    verdict: 'Write a one-page AI use policy before anything else. It costs nothing and covers most of the risk.',
  },
]

// The six doors. Each has a short label for the board, the full question,
// the "why we ask", and the ending you reach if the answer is no.
export const doors = [
  {
    key: 'pattern',
    label: 'A pattern',
    q: 'Is there a task that happens at least weekly and follows a recognisable pattern?',
    why: 'Think quoting, chasing invoices, answering the same enquiry, writing up the same report. Not "we are busy" in general.',
    no: {
      h: 'AI is a pattern machine.',
      t: 'Without a repeating task there is nothing to automate and nothing to speed up. Chat tools might save the odd hour, but nothing worth building around.',
      first: 'Keep a two-week log of what the team actually does. The repeating task usually shows up by day four.',
    },
  },
  {
    key: 'written',
    label: 'Written down',
    q: 'Is the information that task needs written down somewhere, not just in someone’s head?',
    why: 'Emails, documents, a spreadsheet, a system. If the process lives entirely in one person’s memory, a tool has nothing to read.',
    no: {
      h: 'AI can only work with what it can read.',
      t: 'Document the process first. A half-day writing down how the job is actually done will do more for the business than any tool, and it makes AI possible later.',
      first: 'Have the person who does the task narrate it once while someone else types. That is the document.',
    },
  },
  {
    key: 'safety',
    label: 'A safety net',
    q: 'Can the business tolerate occasional mistakes, and does someone check the output before it matters?',
    why: 'Every AI tool is wrong sometimes, and it is wrong confidently. The question is whether a mistake gets caught and whether it can be undone.',
    no: {
      h: 'Confident errors with no safety net.',
      t: 'If a wrong answer is unrecoverable and nobody reviews it, you are not ready. Fix the review step or choose a lower-stakes task.',
      first: 'Pick the version of the task where a mistake costs an hour, not a client. Start there.',
    },
  },
  {
    key: 'worth',
    label: 'Worth the hours',
    q: 'Does that task cost the team more than about five hours a week, or hold up something that makes money?',
    why: 'Be honest about the number. Setup, testing and maintenance are real hours too.',
    no: {
      h: 'The setup will cost more than it saves.',
      t: 'Give the people who want one a chat assistant on a business plan and leave it there. Do not build anything.',
      first: 'Run the Automation Opportunity Finder on this site to see whether a different task clears the bar.',
    },
  },
  {
    key: 'data',
    label: 'The data can move',
    q: 'Can the data involved legally and safely leave your systems, or can you afford a controlled setup where it does not have to?',
    why: 'Client financial records, health information, privileged material, and anything your licensee restricts all need an answer here first.',
    no: {
      h: 'The compliance question comes first.',
      t: 'Until privacy, confidentiality or licensee rules are settled, AI is a liability rather than a help. That may mean a private deployment, or it may mean a different task.',
      first: 'Talk to your licensee, professional body or adviser before anything else. Read the sector note below for what to ask.',
    },
  },
  {
    key: 'owner',
    label: 'An owner',
    q: 'Is there one person who will own this for ninety days?',
    why: 'Not a committee. One name, with the authority to switch it off if it is not working.',
    no: {
      h: 'Tools without an owner die within a quarter.',
      t: 'This is the most common reason AI projects fail in small business. Find the owner first, or wait until you can.',
      first: 'Name the person in the next team meeting. If nobody wants it, that is your answer for now.',
    },
  },
]

export const win = {
  h: 'AI will probably help.',
  t: 'You have a repeating task, written-down information, a review step, real hours at stake, a clear data position and an owner. That is more than most businesses can say.',
  list: [
    'Start at level one this week and make the tools a habit.',
    'Build one workflow at level two around the task from the first door.',
    'Run it beside the manual process for a month before trusting it.',
  ],
}

export const toolTypes = [
  { name: 'Chat assistants', fit: 'A person types, the tool answers. Drafting, summarising, rewriting, brainstorming, explaining. Good for a person who already knows what good looks like and wants to go faster.', eg: 'ChatGPT, Claude, Gemini, Copilot chat' },
  { name: 'Built-in features', fit: 'AI already inside software you pay for: meeting summaries, email drafts, spreadsheet formulas, photo editing. Good for nearly everyone, because the setup cost is zero and the data stays where it already is.', eg: 'Microsoft 365 Copilot, Google Workspace, Xero, HubSpot, Canva' },
  { name: 'Workflow automation', fit: 'Rules that move information between systems, with an AI step in the middle to read, classify or write something. Good for repetitive admin with a clear trigger, like "new enquiry arrives, draft a reply, log it in the CRM".', eg: 'Zapier, Make, Power Automate, n8n' },
  { name: 'Agents', fit: 'Software that takes a goal, works out the steps, uses other tools and comes back with a result. Powerful, less predictable, and needs guardrails. Good for multi-step work where a human reviews the output before it matters.', eg: 'Claude Code, Copilot agents, custom builds on the major AI platforms' },
  { name: 'Custom and trained models', fit: 'A model built or fine-tuned on your own data, or a private deployment for confidentiality. Good for businesses with a large, specific dataset and a compliance reason to keep it in-house. Rarely the right first step.', eg: 'Azure OpenAI, AWS Bedrock, on-premise open models' },
]

export const levels = [
  {
    name: 'Level one: switch on what you already pay for',
    meta: ['$0 to $50 per person per month', 'A day', 'Low risk'],
    items: [
      'Turn on the AI features inside Microsoft 365, Google Workspace, Xero or your CRM.',
      'Give the two or three people who write the most a paid chat assistant on a business plan.',
      'Write the one-page use policy. Name what is allowed in and what is not.',
    ],
    warn: 'Stop here if nobody in the business uses these tools daily after a month. The problem is not the tool.',
  },
  {
    name: 'Level two: automate one repeating workflow',
    meta: ['$2k to $15k to build, $100 to $500 a month to run', 'Two to six weeks', 'Medium risk'],
    items: [
      'Pick one process that happens at least weekly, follows a pattern and has a person who checks the result.',
      'Connect the systems it touches with an automation platform and an AI step for the reading or writing.',
      'Run it beside the manual process for a month before trusting it.',
    ],
    warn: 'Stop here if the process changes every time someone new does it. Automate the process after you fix it, not before.',
  },
  {
    name: 'Level three: agents and private deployments',
    meta: ['$20k upward, plus ongoing', 'Months', 'High risk'],
    items: [
      'Custom agents that handle multi-step work, or a private model deployment because your data cannot leave a controlled environment.',
      'Needs someone technical on the inside, a real budget and monitoring after launch.',
      'Justified when level two is running well and the volume or sensitivity demands more.',
    ],
    warn: 'Almost nobody should start here. If a vendor proposes it first, ask what happened at levels one and two.',
  },
]
