// Insights: categorised articles for the Tools & Insights section.
//
// COMPLIANCE: GBX Professional Services does not hold an AFSL. Investment and
// financial-education pieces here are GENERAL INFORMATION and education only.
// They must not read as personal financial advice or a product recommendation.
// Keep them principle-based and non-specific, and keep the general-information
// line where investing is discussed.
//
// STYLE: no em dashes. Write the firm name in full as "GBX Professional Services".
// Article body blocks are { type: 'p' | 'h', text }. Newest first.

export const insightCategories = [
  { slug: 'ai', label: 'AI' },
  { slug: 'marketing', label: 'Marketing' },
  { slug: 'analytics', label: 'Business Analytics' },
  { slug: 'business-tools', label: 'New Business Tools' },
  { slug: 'sales', label: 'Sales' },
  { slug: 'investment', label: 'Investment Research' },
  { slug: 'education', label: 'Financial Education' },
]

const GENERAL_INFO =
  'This is general information and education only. It does not take account of your objectives, financial situation or needs and is not personal financial advice. GBX Professional Services does not hold an Australian Financial Services Licence. Consider speaking with a licensed adviser before acting on anything here.'

export const articles = [
  {
    slug: 'what-a-business-diagnostic-looks-at',
    category: 'analytics',
    title: 'What a ten-day business diagnostic actually looks at',
    date: '2026-09-23',
    readingTime: '5 min read',
    summary:
      'A diagnostic is a short, fixed-scope look at how a business actually runs, done before you commit to a big project. Here is what ten days covers, and what you walk away with.',
    body: [
      { type: 'p', text: 'Most businesses do not need another opinion. They need an accurate picture. A diagnostic is a short, fixed-scope look at how a business actually runs, done before anyone commits to a big project, so the work that follows is aimed at the right problem. Our version runs over ten days. Here is what those ten days actually cover, and what you walk away with.' },
      { type: 'p', text: 'The point of a fixed scope is honesty. You know the cost and the finish date before you start, the work does not sprawl, and there is no incentive to find reasons to keep going. At the end you own a plan, whether or not you do anything else with us.' },
      { type: 'h', text: 'Why ten days, and why it barely touches your calendar' },
      { type: 'p', text: 'Ten days is long enough to look properly and short enough to stay disciplined. The elapsed time is ours, not yours. Across the whole engagement you spend around four to six hours: a kick-off, a few interviews, a short data request and the readout. Everything is scheduled around your calendar so the business keeps running as normal. Nobody downs tools for a fortnight.' },
      { type: 'h', text: 'The numbers, read for what they are telling you' },
      { type: 'p', text: 'The first strand is your numbers. Not an audit, and not a rebuild of your accounts, but a read of what your management figures actually say about the business. Where is the margin, and where is it leaking. Which customers, products or services make money and which quietly cost you. What the trend over the last year or two reveals that a single month hides. Most owners have the data. Fewer have had someone sit with it and ask the awkward questions.' },
      { type: 'h', text: 'The systems and processes, where time and money leak' },
      { type: 'p', text: 'The second strand is how work actually flows. We walk your main systems and the handful of processes that carry the most volume, looking for the friction that caps capacity and margin: the double-handling, the manual steps that could be automated, the handoffs where things stall or get dropped. This is usually where the fastest gains sit, because fixing a process pays back every time the process runs.' },
      { type: 'h', text: 'The people, because the team already knows' },
      { type: 'p', text: 'The third strand is the people. The team doing the work usually knows where the problems are long before the numbers show them. A few structured interviews surface what is obvious on the floor and invisible from the top: the workaround everyone relies on, the report nobody trusts, the bottleneck that has quietly become normal. We are listening for patterns, not collecting complaints.' },
      { type: 'h', text: 'The output, a prioritised plan you own' },
      { type: 'p', text: 'At the end you get two things. A prioritised opportunity map, so you can see where the fastest and most durable gains sit and what each is roughly worth, and a 90-day plan that says what to do first, next and after that. It is written to be used, not filed. You own it. Some clients run it themselves from there, some ask us to deliver specific parts, and either is a good outcome. There is no assumption you will do anything beyond the diagnostic itself.' },
      { type: 'h', text: 'What it is not' },
      { type: 'p', text: 'It is not a sales pitch dressed as a review. It is not a hundred-page report that says what you already knew in longer sentences. And it is not a generic template with your logo on it. The scope is fixed, the plan is specific to your business, and the recommendations are the ones we would act on if the business were ours.' },
      { type: 'h', text: 'How to start' },
      { type: 'p', text: 'If you want to test the water first, the free Business Health Check takes two minutes and gives you a rough read across the same areas, and a diagnostic call costs nothing and carries no obligation. The diagnostic itself is a fixed fee, and if you go on to delivery work with us soon after, that fee is credited in full against it. The aim is simple: an accurate picture, a plan you can act on, and the confidence to spend on the right thing rather than the loudest thing.' },
    ],
  },
  {
    slug: 'compliance-questions-before-adopting-ai',
    category: 'ai',
    title: 'The compliance questions every business should ask before adopting AI',
    date: '2026-09-23',
    readingTime: '6 min read',
    summary:
      'Adopting AI is not only a technology decision, it is a compliance one, and not just for regulated industries. Six questions worth answering before your team starts using AI in earnest.',
    body: [
      { type: 'p', text: 'AI has gone from novelty to normal tool faster than most businesses have written a single rule about it. Staff are already pasting documents into chatbots, drafting emails with AI and trialling tools a vendor demoed last week. That is not a problem to stamp out, it is a wave to steer. The businesses that get value from AI without a nasty surprise are the ones that answer a handful of compliance questions before adoption spreads, not after something goes wrong.' },
      { type: 'p', text: 'None of this is only for banks and law firms. Any business holds information it is obliged to protect, makes decisions it is accountable for, and keeps records it may one day need to produce. AI touches all three. Here are the questions worth answering first, whatever you do.' },
      { type: 'h', text: 'Where does our data go, and who can see it?' },
      { type: 'p', text: 'The single biggest risk in day-to-day AI use is data leaving your control. Consumer chatbots may use what your staff type to improve their models, and may store it on servers in another country. Paste a client list, a contract or a health record into the wrong tool and you may have breached a privacy or confidentiality obligation without realising it.' },
      { type: 'p', text: 'For any tool you are considering, ask: does it train on our inputs, can we turn that off, where is the data stored, and is there an agreement that makes those answers binding? Business-grade versions of the major AI tools usually let you switch training off and offer a data agreement. The free consumer versions often do not. As a working rule, no customer-identifying or confidential information goes into a tool you have not checked against those questions.' },
      { type: 'h', text: 'Who is accountable when AI gets it wrong?' },
      { type: 'p', text: 'AI is confident even when it is wrong. It will invent a figure, a citation or a clause and present it as fact. That is manageable, but only if a person owns the output. The business that sends an AI-drafted quote, letter or report to a customer is responsible for it, exactly as if a junior had written it. The tool is not a party you can blame.' },
      { type: 'p', text: 'So decide, before you adopt, where the human review step sits. Anything that leaves the business, reaches a customer or feeds a real decision gets read by a person who is accountable for it. Build that into the workflow rather than trusting people to remember it under deadline.' },
      { type: 'h', text: 'Do we have a policy people can actually follow?' },
      { type: 'p', text: 'Most AI problems trace back to the absence of a simple rule, not to the technology. A one-page AI policy prevents the majority of them. It names the tools that are approved, says what may and may not be put into them, sets the review step above, and tells people who to ask when they are unsure.' },
      { type: 'p', text: 'Keep it short enough that staff will actually read it. A policy nobody opens is worse than none, because it creates the appearance of control without the substance. The point is to give your team the confidence to use AI well and in the open, rather than quietly and around you.' },
      { type: 'h', text: 'Does our industry add rules?' },
      { type: 'p', text: 'Some industries carry obligations that apply to AI-assisted work just as they do to anything else. If you are in a licensed or regulated field, such as financial services, health or law, your regulator or professional body may have specific guidance, and your existing duties still bind you when AI is in the loop. Check their current position before AI touches regulated decisions or advice.' },
      { type: 'p', text: 'Financial services is a clear example. Providing financial product advice needs an Australian Financial Services Licence whether a person or an AI helped prepare it, because the obligation attaches to the advice, not the software. GBX Professional Services does not hold an AFSL and does not provide financial advice. Our role is to help businesses adopt AI operationally, with the regulated decisions staying inside the licensed businesses that own them.' },
      { type: 'h', text: 'What is the smallest safe place to start?' },
      { type: 'p', text: 'The answer to all of the above is not to ban AI or to wait for perfect certainty. It is to start where the risk is low and the repetition is high. Internal drafting, meeting notes, summarising public research and first-draft marketing rarely touch confidential data or produce a final decision, so they make a sensible first use case for almost any business.' },
      { type: 'p', text: 'Put the one-page policy and an approved-tools list in place, add the human review step, prove the value on a task or two, then expand into higher-stakes work as your confidence and controls grow. Adoption that starts small and safe tends to spread further than a big-bang rollout that trips over its first mistake.' },
      { type: 'h', text: 'The point of the questions' },
      { type: 'p', text: 'The businesses that do well with AI are not the most cautious or the most gung-ho. They are the ones that asked these questions early, wrote down a few answers, and got on with it. If you want a structured read on where AI genuinely helps your business and what to put in place first, the free Will AI actually help guide and the AI Readiness Assessment are a good place to begin.' },
      { type: 'p', text: 'This article is general information, not legal, compliance or financial advice. Your own advisers, and where relevant your licensee or professional body, remain the source of truth on your specific obligations.' },
    ],
  },
  {
    slug: 'benchmarking-are-your-numbers-good',
    category: 'analytics',
    title: 'Benchmarking: how to tell if your numbers are actually good',
    date: '2026-07-15',
    readingTime: '5 min read',
    summary:
      'A number on its own tells you very little. Benchmarking gives it a reference point, so you can tell the difference between a good month and a lucky one.',
    body: [
      { type: 'p', text: 'Most owners know their revenue and their bank balance. Far fewer can say whether those numbers are good, because a number on its own has no reference point. A thirty percent gross margin might be excellent in one industry and alarming in another. Benchmarking is simply the practice of giving your numbers something to be measured against.' },
      { type: 'h', text: 'Three reference points that matter' },
      { type: 'p', text: 'Benchmark against your own past, first. A metric trending in the right direction over twelve months tells you more than any single figure, because it filters out the noise of a good or bad week. Then benchmark against your plan: the target you set at the start of the year is a deliberate statement of what good looks like for you, and the gap to it is the most honest scorecard you have.' },
      { type: 'p', text: 'Finally, where you can find it, benchmark against your industry. Industry association surveys, published salary and margin guides, and lender or franchisor data are more reliable than a competitor rumour or a number someone quoted at a conference. Treat any single external figure as a rough guide rather than gospel.' },
      { type: 'h', text: 'A worked example' },
      { type: 'p', text: 'Say your revenue grew twelve percent last year and you feel good about it. Benchmarked against your own prior years, where you grew eighteen and twenty percent, growth is actually slowing. Benchmarked against a plan that assumed fifteen percent, you missed. Benchmarked against an industry running hot at twenty-five percent, you lost ground. The same twelve percent looks like a win, a miss, or a warning depending on the reference point, and only the references tell you which.' },
      { type: 'h', text: 'Pick a small set and hold to it' },
      { type: 'p', text: 'The temptation is to benchmark everything. Resist it. Choose a handful of measures that actually drive your business, such as gross margin, revenue per employee, client retention and utilisation, and track them consistently against the same three references each quarter. A few benchmarks watched every quarter beat twenty reviewed once a year and then forgotten.' },
      { type: 'p', text: 'The goal is not a perfect comparison, because industry data is never a perfect match for your business. The goal is to move from a private hunch about how you are doing to a defensible view you can act on, and to notice a problem while it is still small enough to fix cheaply.' },
    ],
  },
  {
    slug: 'diversification-the-one-idea',
    category: 'education',
    title: 'Diversification: the one idea most worth understanding',
    date: '2026-06-16',
    readingTime: '5 min read',
    summary:
      'Of all the concepts in investing, diversification is the one that rewards a little study the most. Here is the plain-language version, as general education.',
    body: [
      { type: 'p', text: 'If you only ever understand one idea in investing, make it diversification. It is the closest thing the field has to a free lunch, and it is often misunderstood as simply owning a lot of things.' },
      { type: 'p', text: 'Diversification is really about owning things that do not all move together. Two investments that rise and fall in lockstep give you little protection, no matter how many of them you hold. The benefit comes from combining assets whose ups and downs partly offset each other, so the overall ride is smoother than any single holding on its own.' },
      { type: 'h', text: 'The mistake of false diversification' },
      { type: 'p', text: 'A common trap is owning ten things that are really the same bet. Five technology funds, or a portfolio built entirely from one country and one currency, feels diversified because it is many holdings, but it behaves like one. Genuine diversification spreads across things that respond differently to the same events, so that when one part struggles another may hold up.' },
      { type: 'h', text: 'Why it matters for ordinary people' },
      { type: 'p', text: 'A smoother ride is not just more comfortable. It makes it easier to stay invested through difficult periods, and staying invested is where most long-term results actually come from. The investor who panics and sells at the bottom rarely does well, however clever the original plan. Diversification is, in part, a behavioural tool: it keeps the swings small enough that you can hold your nerve.' },
      { type: 'p', text: 'It has limits, too. In a severe, broad downturn, many things fall together for a while, and diversification will not spare you entirely. It reduces the risk of any single bet sinking you; it does not remove market risk altogether. Understanding that trade-off, rather than any specific product, is the education worth having.' },
      { type: 'p', text: GENERAL_INFO },
    ],
  },
  {
    slug: 'reading-market-commentary',
    category: 'investment',
    title: 'Reading market commentary without losing your head',
    date: '2026-05-14',
    readingTime: '5 min read',
    summary:
      'Financial media is built to capture attention, not to inform decisions. A few habits help you take what is useful from market commentary and leave the rest.',
    body: [
      { type: 'p', text: 'There has never been more market commentary available, and never been easier to be misled by it. The financial media exists partly to inform and partly to capture attention, and the two goals pull in different directions. A calm, accurate headline rarely gets clicked, so the loudest voices are not always the most useful ones.' },
      { type: 'h', text: 'Separate news from noise' },
      { type: 'p', text: 'Ask of any piece of commentary: does this change anything I would actually do? Most does not. Daily price moves, confident forecasts and dramatic predictions make for engaging reading but poor inputs to a long-term plan. The signal is usually in the slow, structural stories, the shift in interest rates over years or the change in an industry, not in the fast ones that fill a Tuesday.' },
      { type: 'h', text: 'Check the incentive' },
      { type: 'p', text: 'Notice who is speaking and what they gain. A commentator selling a forecast, a fund promoting a theme, or a platform that profits when you trade more all have reasons to sound certain and urgent. That does not make them wrong, but it is worth knowing before you weigh their view. The most trustworthy sources tend to describe uncertainty honestly rather than paper over it with confidence.' },
      { type: 'h', text: 'Beware the compelling story' },
      { type: 'p', text: 'The riskiest commentary is not the obviously silly kind, it is the well-argued narrative that makes a single outcome feel inevitable. Markets are driven by many forces at once, and a clean story usually leaves most of them out. When a piece makes you feel certain, that is the moment to slow down, not speed up.' },
      { type: 'p', text: 'Good research is a tool for thinking, not a substitute for it. The aim of reading commentary is a better-informed mind and a handful of good questions, not a running instruction to buy or sell.' },
      { type: 'p', text: GENERAL_INFO },
    ],
  },
  {
    slug: 'knowledge-tools-that-scale',
    category: 'business-tools',
    title: 'Knowledge tools that scale with your team',
    date: '2026-04-15',
    readingTime: '4 min read',
    summary:
      'The moment a second person joins, what lives only in your head becomes a bottleneck. A light knowledge system fixes it before it becomes a problem.',
    body: [
      { type: 'p', text: 'In a business of one, the knowledge lives in your head and that works fine. The moment a second or third person joins, everything you know but have never written down becomes a bottleneck, and every question routes back through you. The work you cannot delegate is almost always the work you have never documented.' },
      { type: 'h', text: 'Start with a single home for how things are done' },
      { type: 'p', text: 'You do not need an elaborate system. A well-organised shared workspace, a wiki, a structured set of folders, or a dedicated tool such as Notion, Confluence or a similar product, is enough to begin. The discipline that matters is having one agreed place where the answer to how do we do this lives, so people stop reinventing it or asking you.' },
      { type: 'h', text: 'Write it as you do it' },
      { type: 'p', text: 'The cheapest time to document a process is the moment you run it. The next time you onboard a client, close the month, or handle a complaint, capture the steps as you go, in plain language, with the actual links and templates attached. Six of those and you have a genuine operations manual, built with almost no extra effort and, crucially, accurate because it describes what you really do rather than what you meant to do.' },
      { type: 'h', text: 'Keep it alive' },
      { type: 'p', text: 'A knowledge base rots if nobody owns it. Give each area an owner, review it lightly every quarter, and make updating it part of finishing a task rather than a separate chore. A short, current guide beats an exhaustive one that everyone has quietly learned not to trust.' },
      { type: 'p', text: 'Knowledge tools earn their keep quietly. They shorten training, reduce the questions that only you can answer, and make the business worth more, because a business that can run without its founder in the room is a more valuable and more sellable business.' },
    ],
  },
  {
    slug: 'privacy-data-rising-bar-for-marketers',
    category: 'marketing',
    title: 'Privacy, data and the rising bar for marketers',
    date: '2026-03-16',
    readingTime: '5 min read',
    summary:
      'Expectations around personal data keep tightening, in law and in public sentiment. For marketers, especially in regulated sectors, that is a shift to plan around, not against.',
    body: [
      { type: 'p', text: 'The direction of travel on personal data is clear and consistent: more consent, more transparency, and more accountability for how businesses collect and use it. Reforms to privacy law, tighter platform rules, the decline of third-party tracking cookies, and a public that is simply more wary all point the same way.' },
      { type: 'h', text: 'What this means in practice' },
      { type: 'p', text: 'Marketing that depends on quietly harvesting data and following people around the internet is becoming both harder and riskier. Marketing built on permission, where people choose to hear from you because the value is clear, is becoming the durable option. That is a good change for businesses with something genuine to say, and an awkward one for those relying on borrowed attention.' },
      { type: 'h', text: 'Own your audience' },
      { type: 'p', text: 'The practical response is to invest in relationships you actually control: an email list people opted into, a genuinely useful newsletter, content that earns a return visit. First-party data, given willingly, is more accurate, more durable and less exposed to the next platform policy change than anything rented from an ad network. It compounds while rented audiences reset.' },
      { type: 'h', text: 'Regulated sectors carry an extra layer' },
      { type: 'p', text: 'For financial services and other regulated industries, advertising rules sit on top of privacy law. Claims must be accurate and not misleading, records may need to be kept, and the line between general information and regulated advice must be respected. The safe path is to design campaigns with those obligations in mind from the start, rather than checking them at the end when the creative is already made.' },
      { type: 'p', text: 'None of this is a reason to retreat from marketing. It is a reason to build on first-party relationships, clear consent and honest claims, which is where trust was always going to be won.' },
    ],
  },
  {
    slug: 'ai-governance-starting-point',
    category: 'ai',
    title: 'AI governance for small business: a practical starting point',
    date: '2026-02-17',
    readingTime: '5 min read',
    summary:
      'You do not need a policy department to use AI responsibly. You need a few clear rules about data, review and accountability that fit on a single page.',
    body: [
      { type: 'p', text: 'Governance sounds like something only large organisations need. In reality, the smaller the business, the more a few simple AI rules pay off, because there is no committee to catch a mistake before it reaches a client and no legal team to clean it up afterward.' },
      { type: 'h', text: 'Three rules that cover most of the risk' },
      { type: 'p', text: 'First, be careful what you paste in. Do not put client-identifying information, credentials or anything confidential into a public AI tool unless you know how that tool handles data and whether it trains on your inputs. Second, a human reviews anything that goes to a client or a regulator: AI drafts, people approve. Third, someone owns each use case, so accountability never falls into a gap between staff who assumed the other had checked.' },
      { type: 'h', text: 'Know the failure modes' },
      { type: 'p', text: 'AI tools are fluent and confident even when they are wrong, they can invent facts and citations that look real, and they can reflect bias in their training. None of that makes them unusable. It means the review step is not optional and that AI belongs on tasks where a person can readily check the output, not where a confident error would quietly cause harm.' },
      { type: 'h', text: 'Write it down and keep it short' },
      { type: 'p', text: 'A one-page policy that people actually read beats a thirty-page one that sits in a drawer. Name the tools you allow, the data you will not share, the review step before anything ships, and who to ask when unsure. Revisit it as the tools change, which they will, and tell new starters it exists on day one.' },
      { type: 'p', text: 'Good governance is not about slowing AI down. It is about being able to adopt it confidently, because you have decided in advance where the guardrails sit and everyone knows the rules.' },
    ],
  },
  {
    slug: 'referrals-by-design',
    category: 'sales',
    title: 'Referrals by design, not by luck',
    date: '2026-01-19',
    readingTime: '5 min read',
    summary:
      'Most businesses say referrals are their best source of clients, then leave them entirely to chance. A light, repeatable system turns goodwill into a reliable channel.',
    body: [
      { type: 'p', text: 'Ask owners where their best clients come from and most say referrals. Ask what their referral system is and most go quiet. The very channel they rate most highly is the one they leave entirely to luck, hoping happy clients will remember to mention them at the right moment to the right person.' },
      { type: 'h', text: 'Make it easy to refer you' },
      { type: 'p', text: 'People refer when they know what you do, trust that you will look after their contact, and can describe you in a single sentence. Give them that sentence. A clear, simple description of who you help and the problem you solve travels far better than a list of services, because the person referring you has to repeat it from memory in a hallway conversation.' },
      { type: 'h', text: 'Ask at the right moment' },
      { type: 'p', text: 'The best time to ask is just after you have delivered something the client is genuinely pleased with: a result landed, a problem solved, a thank-you received. Not a mass campaign, just a natural, specific request. Instead of a vague do you know anyone, try is there anyone else in your network dealing with this exact problem. Specificity jogs the memory and makes the ask easy to answer.' },
      { type: 'h', text: 'Close the loop' },
      { type: 'p', text: 'When a referral comes in, thank the person who made it, and let them know how it went, within the bounds of confidentiality. People refer more when they can see it was welcomed and handled well. A referral that vanishes into silence quietly teaches them not to bother again.' },
      { type: 'p', text: 'A referral system is not pushy. It is simply refusing to leave your strongest channel to chance, and giving happy clients an easy, well-timed way to do something they were already inclined to do.' },
    ],
  },
  {
    slug: 'the-dashboard-trap',
    category: 'analytics',
    title: 'The dashboard trap: measuring what actually matters',
    date: '2025-12-15',
    readingTime: '5 min read',
    summary:
      'A dashboard full of numbers can feel like insight while delivering none. The fix is fewer metrics, chosen because they change a decision.',
    body: [
      { type: 'p', text: 'Modern tools make it trivial to build a dashboard with forty metrics on it. That is exactly the problem. A wall of numbers looks like control and often delivers the opposite, because attention is finite and most of those numbers never change a decision. The more crowded the screen, the less anyone actually looks at it.' },
      { type: 'h', text: 'The test for every metric' },
      { type: 'p', text: 'Before a number earns a place on your dashboard, ask: if this moved sharply, would I do something differently? If the honest answer is no, it is a vanity metric. Interesting, perhaps, but not a management tool, and it dilutes attention from the numbers that would actually prompt action. Cut it, or move it to a report you review occasionally rather than the daily view.' },
      { type: 'h', text: 'Lead and lag together' },
      { type: 'p', text: 'The best dashboards pair lagging measures, which tell you what happened, with leading ones, which hint at what is coming. Revenue and profit are lags: by the time they move, the cause is months old. Qualified enquiries, pipeline, quote-to-win rate and utilisation are leads. Watching only the lag is like driving by the rear-view mirror, and wondering why the surprises keep arriving.' },
      { type: 'h', text: 'Give every number an owner and a target' },
      { type: 'p', text: 'A metric with no owner is nobody job to move, and a metric with no target cannot be judged good or bad. For each number that survives the test above, name the person accountable for it and the level you are aiming for. That turns a dashboard from a wall of trivia into a short list of live conversations.' },
      { type: 'p', text: 'A good dashboard is mostly white space. A handful of numbers you trust, each owned and each with a target, watched often, will run a business better than a crowded screen nobody quite believes.' },
    ],
  },
  {
    slug: 'fees-matter-the-quiet-drag',
    category: 'education',
    title: 'Fees matter: the quiet drag of costs over time',
    date: '2025-11-17',
    readingTime: '5 min read',
    summary:
      'Costs feel small in any single year and compound into something large over decades. Understanding that arithmetic is basic financial literacy, offered here as general education.',
    body: [
      { type: 'p', text: 'A fee of one or two percent sounds trivial, and in a single year it nearly is. Over an investing lifetime it is anything but, because the same compounding that grows your money also grows the cost of every fee you pay along the way.' },
      { type: 'h', text: 'Why small percentages become large sums' },
      { type: 'p', text: 'Every dollar paid in fees is a dollar that is no longer invested, and it is also all the growth that dollar would have earned in the years that followed. Compounded across decades, a difference of one percent a year can add up to a meaningful share of a final balance. The arithmetic is not intuitive, which is exactly why it is worth learning, and why the effect is so easy to underestimate when you sign up.' },
      { type: 'h', text: 'Look for the fees you cannot see' },
      { type: 'p', text: 'Some costs are obvious, such as an advertised management fee. Others are quieter: platform fees, transaction costs, the spread between buying and selling prices, and fees buried inside products held within other products. You are entitled to ask for the total cost, sometimes described as an all-in or total-cost figure, and to have it explained in dollars, not just percentages.' },
      { type: 'h', text: 'What to do with the idea' },
      { type: 'p', text: 'The point is not that cheapest is always best. Some services are genuinely worth paying for, and the right question is value for money, not price alone. The point is to know what you are paying, in dollars as well as percentages, and to weigh it deliberately against what you receive rather than letting it drift unexamined for twenty years.' },
      { type: 'p', text: GENERAL_INFO },
    ],
  },
  {
    slug: 'investment-platforms-falling-cost-of-access',
    category: 'investment',
    title: 'Investment platforms and the falling cost of access',
    date: '2025-10-15',
    readingTime: '5 min read',
    summary:
      'The cost and friction of investing have fallen dramatically in a decade. That is mostly good, and it comes with a few new things worth understanding.',
    body: [
      { type: 'p', text: 'A decade ago, investing meant phone calls, paperwork and brokerage costs that made small or frequent trades uneconomic. Today a low-cost platform and a few taps do the same job. The fall in the cost and friction of access is one of the more important quiet changes in personal finance, and it has brought millions of new investors into the market.' },
      { type: 'h', text: 'What got better' },
      { type: 'p', text: 'Lower costs, fractional investing and simple interfaces have opened the door to people who were previously priced or intimidated out. Building a diversified position no longer requires a large sum or a broker on the phone, and regular automated investing has never been easier to set up. For patient, long-term investors, that is a genuine improvement.' },
      { type: 'h', text: 'What to keep an eye on' },
      { type: 'p', text: 'Frictionless access cuts both ways. The same ease that helps you invest steadily also makes it easy to trade impulsively, chase trends, check the balance ten times a day, or treat investing like a game. Some platforms are designed, deliberately, to encourage exactly that, because activity can earn them money. The tool is neutral; how it is used is not.' },
      { type: 'h', text: 'Practical questions before you choose one' },
      { type: 'p', text: 'It is reasonable to ask how a platform makes its money, what happens to your holdings if the platform itself fails, what it costs in total to buy, hold and sell, and how easily you could move your investments elsewhere later. Boring questions, but they matter more over decades than the slickness of the app.' },
      { type: 'p', text: GENERAL_INFO },
    ],
  },
  {
    slug: 'writing-prompts-that-work',
    category: 'ai',
    title: 'How to write AI prompts that actually work',
    date: '2025-09-12',
    readingTime: '6 min read',
    summary:
      'Most AI disappointment is a prompting problem, not a model problem. A simple, repeatable structure gets you dramatically better results, and our Prompt Optimizer builds on it, tailoring the prompt to the specific AI model you are using.',
    tool: {
      href: '/tools/prompt-optimizer/',
      heading: 'Try it without the hand-assembly',
      body: 'Our Prompt Optimizer applies this structure for you and tailors the result to the specific AI model you are using.',
      label: 'Open the Prompt Optimizer',
    },
    body: [
      { type: 'p', text: 'If you have ever asked an AI for help and got back something vague, generic or subtly wrong, the model is usually not the problem. The prompt is. A large language model can only work with what you give it, and most prompts give it far too little to go on.' },
      { type: 'p', text: 'The good news is that better prompting is a skill, not a talent. A handful of habits will lift the quality of almost everything you get back. Here is the structure we use, and the one our Prompt Optimizer builds for you automatically.' },
      { type: 'h', text: 'Give it a role' },
      { type: 'p', text: "Start by telling the model who it should be. 'You are a senior financial-services compliance analyst' produces a very different answer to no framing at all. A role sets the vocabulary, the depth and the assumptions the model brings to the task." },
      { type: 'h', text: 'Supply the context' },
      { type: 'p', text: 'The model cannot see what you can see. Tell it who the output is for, what has happened so far, and any constraints that matter. A paragraph of context is often worth more than a page of instructions.' },
      { type: 'h', text: 'State the task plainly' },
      { type: 'p', text: "Be specific about the one thing you want. 'Summarise this in five bullet points a busy director can scan' beats 'help me with this'. If there are several things, number them, and consider running them as separate prompts." },
      { type: 'h', text: 'Set the constraints' },
      { type: 'p', text: 'Length, tone, what to avoid, the audience, the reading level. Constraints are not limits on the model, they are how you get the specific answer you actually need instead of a plausible average of everything.' },
      { type: 'h', text: 'Describe the output format' },
      { type: 'p', text: 'Ask for the exact shape you want to receive: a table, a list, a short email, JSON, headings. Telling the model how to lay the answer out saves you the reformatting and makes the result usable straight away.' },
      { type: 'h', text: 'Show an example' },
      { type: 'p', text: 'If you have a sample of the style or format you want, paste it in and say more like this. One good example teaches the model faster than three paragraphs of description, especially for tone and structure.' },
      { type: 'h', text: 'Iterate' },
      { type: 'p', text: 'Your first prompt is a draft. Read the response, notice where it missed, and add the missing context or constraint. Two or three quick rounds will get you further than trying to write the perfect prompt in one go.' },
      { type: 'p', text: 'Put those habits together and you have a prompt that gives a model a real chance of being useful. If you would rather not assemble it by hand every time, our Prompt Optimizer does the work for you, and goes a step further by tailoring the result to the specific AI model you are using.' },
    ],
  },
  {
    slug: 'automations-worth-setting-up-first',
    category: 'business-tools',
    title: 'The automations worth setting up first',
    date: '2025-08-14',
    readingTime: '5 min read',
    summary:
      'You can automate almost anything now, which is exactly why most people automate the wrong things. Start where the work is repetitive, rule-based and frequent.',
    body: [
      { type: 'p', text: 'Automation has never been more accessible. Tools that connect your apps together can move information around without anyone touching it. The risk is not that you cannot automate enough, it is that you automate the wrong things and add fragile complexity for little gain, then spend more time maintaining the automation than it ever saved.' },
      { type: 'h', text: 'The three-part test' },
      { type: 'p', text: 'A task is a good candidate when it is repetitive, rule-based and frequent. Repetitive means it happens the same way each time. Rule-based means the decisions can be written down as clear if-this-then-that logic. Frequent means it happens often enough that the time saved is real. Tasks that fail any of the three are usually better left to a person, at least for now.' },
      { type: 'h', text: 'Good first candidates' },
      { type: 'p', text: 'Moving new enquiries into your CRM, sending a consistent welcome sequence, chasing unpaid invoices, scheduling and reminding for meetings, and backing up important files are classic starting points. They are dull, they are rule-based, and they are exactly the sort of thing that quietly slips when a business is busy, which is when they matter most.' },
      { type: 'h', text: 'Automate the process, not the mess' },
      { type: 'p', text: 'Automating a broken process just makes the mess happen faster. Tidy and document the steps by hand first, until they are genuinely repeatable, then automate the version that works. It is also wise to build in a way to see when an automation fails, because a silent break that stops chasing invoices for a month is worse than no automation at all.' },
      { type: 'p', text: 'Automate the boring and predictable, keep judgement in human hands, document what you have built, and check now and then that it is still doing what you think it is.' },
    ],
  },
  {
    slug: 'compliance-aware-marketing-financial-services',
    category: 'marketing',
    title: 'Compliance-aware marketing for financial services',
    date: '2025-07-15',
    readingTime: '5 min read',
    summary:
      'Marketing a financial services business means growing demand without crossing regulatory lines. Done well, compliance is not a brake on marketing, it is what makes it trustworthy.',
    body: [
      { type: 'p', text: 'Marketing in financial services carries an obligation most industries do not face. What you say, how you say it, and the impression you leave are all subject to rules designed to protect consumers. Treating those rules as an afterthought is how good businesses end up in avoidable trouble, sometimes over a single careless social post.' },
      { type: 'h', text: 'The line that matters most' },
      { type: 'p', text: 'The clearest risk is blurring general information and regulated advice. Educational content that helps people understand their options is very different from a recommendation about a specific product or a specific person situation. Marketing should stay firmly on the general-information side unless the business is licensed to cross it, and should say so plainly where it matters.' },
      { type: 'h', text: 'Accurate, balanced, not misleading' },
      { type: 'p', text: 'Claims need to be accurate and capable of being substantiated. Past results are not a promise of future ones, and benefits should not be presented without the relevant risks and costs. This is not just legally safer, it is better marketing, because balanced claims are more believable and the audience you want is the kind that notices the difference.' },
      { type: 'h', text: 'Build the record as you go' },
      { type: 'p', text: 'Regulated marketing benefits from a light paper trail: who approved a campaign, what claims it made, and what evidence sat behind them. It sounds bureaucratic, but a simple approval step and a saved copy of each asset turns a future query from a scramble into a filing exercise, and it makes the whole team more careful in the first place.' },
      { type: 'p', text: 'The businesses that market well in this sector treat compliance as a design input, not a review gate. Build the obligations into the brief, and the creative that follows is both safer and more credible. GBX Professional Services works alongside licensed firms to do exactly that, without providing financial services itself.' },
    ],
  },
  {
    slug: 'chatbot-to-colleague-ai-grew-up',
    category: 'ai',
    title: 'From chatbot to colleague: how AI tools grew up',
    date: '2025-06-16',
    readingTime: '5 min read',
    summary:
      'AI assistants moved from novelty to genuinely useful in a remarkably short time. Understanding what changed helps you judge where they fit in your business.',
    body: [
      { type: 'p', text: 'It is easy to forget how quickly AI assistants went from party trick to working tool. Early versions were impressive but unreliable, confident and frequently wrong. In a short span they became capable enough to sit inside real workflows, and that shift is worth understanding if you want to judge where they belong in your business.' },
      { type: 'h', text: 'What actually changed' },
      { type: 'p', text: 'Three things matured together. The models became more capable and more consistent. They gained the ability to work with your own documents and data rather than only their training, so answers could be grounded in your reality. And they moved from a chat window into the tools people already use, so the help arrives where the work happens instead of in a separate tab.' },
      { type: 'h', text: 'From answering to doing' },
      { type: 'p', text: 'The larger change is from tools that answer questions to tools that carry out tasks: drafting, summarising, extracting, and increasingly taking multi-step actions under supervision. That is more useful and it raises the stakes, because a tool that acts can also act wrongly at scale. It is why a review step and clear boundaries matter more now, not less.' },
      { type: 'h', text: 'What has not changed' },
      { type: 'p', text: 'The tools are still fluent guessers, not sources of truth. They still need context to be useful and a human to be trusted. The businesses getting value are not the ones with the most advanced model; they are the ones that picked the right tasks and put sensible checks around them.' },
      { type: 'p', text: 'The practical takeaway is not to chase every release. It is to recognise that these tools crossed the line from novelty to genuinely useful, and to find the two or three places they save your business real time.' },
    ],
  },
  {
    slug: 'onboarding-new-clients-so-they-stay',
    category: 'sales',
    title: 'Onboarding new clients so they actually stay',
    date: '2025-05-15',
    readingTime: '5 min read',
    summary:
      'Winning a client is expensive. Losing them in the first ninety days wastes all of it. A deliberate onboarding process is the cheapest retention work you will ever do.',
    body: [
      { type: 'p', text: 'A great deal of effort goes into winning a new client and comparatively little into the first few weeks afterward. That is the wrong way round. The early experience sets the tone for the whole relationship, and a shaky start is expensive to recover from, if you get the chance to recover at all.' },
      { type: 'h', text: 'The first weeks decide the relationship' },
      { type: 'p', text: 'New clients are quietly asking one question: did I make the right decision. Everything in onboarding should answer yes. Clear next steps, a warm welcome, an early and visible win, and no dropped balls all reassure them that the confidence they placed in you was justified. Silence, confusion or a slow start whisper the opposite, at exactly the moment they are most alert to it.' },
      { type: 'h', text: 'Engineer an early win' },
      { type: 'p', text: 'Find something valuable you can deliver in the first week or two, even if the main work takes months. A quick audit, a useful template, a fixed nagging problem. An early win converts hope into evidence, and gives the client something concrete to tell the colleague who asked whether hiring you was a good idea.' },
      { type: 'h', text: 'Make it a process, not a scramble' },
      { type: 'p', text: 'Onboarding should not depend on who happens to be handling it or how busy the week is. Write down the steps, the timing and the owner of each. A simple checklist ensures every client gets the same considered start, even when you are stretched, which is precisely when standards tend to slip.' },
      { type: 'p', text: 'Good onboarding is retention work disguised as admin. It reduces early churn, sets expectations, and turns a nervous new client into a confident long-term one who refers others.' },
    ],
  },
  {
    slug: 'messy-spreadsheet-to-single-source-of-truth',
    category: 'analytics',
    title: 'From messy spreadsheet to single source of truth',
    date: '2025-04-15',
    readingTime: '5 min read',
    summary:
      'Most small businesses run on spreadsheets that have quietly become unreliable. You do not need to replace them, you need to make one of them the version everyone trusts.',
    body: [
      { type: 'p', text: 'Behind most small businesses is a spreadsheet that started tidy and grew wild. Three versions with slightly different numbers, a tab nobody understands, a formula someone broke in March and nobody noticed until June. It still runs the business, and nobody quite trusts it, so decisions quietly drift back to gut feel.' },
      { type: 'h', text: 'The problem is not spreadsheets' },
      { type: 'p', text: 'Spreadsheets are a fine tool, and for many businesses they are the right one for years. The problem is having several competing versions of the truth. When two reports disagree, people stop believing either, and the numbers lose their authority. The fix is to nominate one source that everyone agrees is the real one, and to treat every other copy as disposable.' },
      { type: 'h', text: 'A few habits that restore trust' },
      { type: 'p', text: 'Keep raw data separate from calculations and from presentation, so a formatting change can never corrupt a number. Give each figure one home and reference it everywhere else rather than retyping it. Date and label versions so there is never a question of which is current. Lock or protect the cells that should not be edited. None of this is advanced, and together it turns a fragile file into something dependable.' },
      { type: 'h', text: 'Know when you have outgrown it' },
      { type: 'p', text: 'When several people need to edit at once, when the file is slow or enormous, or when a mistake would be expensive and hard to spot, it is time to move to a proper tool, a database, or a lightweight app. The signal is friction and risk, not a rule about size. Until then, one clean, trusted, well-structured file will serve you well.' },
      { type: 'p', text: 'A single source of truth is not about software. It is about everyone looking at the same numbers and believing them, which is where good decisions start.' },
    ],
  },
  {
    slug: 'compounding-explained',
    category: 'education',
    title: 'Compounding, explained without the hype',
    date: '2025-03-17',
    readingTime: '5 min read',
    summary:
      'Compounding is described as magic so often that the actual mechanism gets lost. Here is the plain version, and why time matters more than timing, offered as general education.',
    body: [
      { type: 'p', text: 'Compounding is talked about so breathlessly that the real idea often disappears behind the hype. Stripped back, it is simple: when your returns themselves start earning returns, growth builds on growth, and the effect gets larger the longer it runs.' },
      { type: 'h', text: 'Why time does the heavy lifting' },
      { type: 'p', text: 'In the early years compounding looks unremarkable, which is why so many people give up on it. The impressive part comes later, because each period builds on a larger base than the one before, so the gains accelerate. That is why starting earlier, even with less, often beats starting later with more. Time in the market, not perfect timing, is what compounding rewards.' },
      { type: 'h', text: 'What breaks it' },
      { type: 'p', text: 'Compounding depends on leaving the base intact and letting it grow. Dipping in and out, reacting to every scare, and paying high ongoing costs all interrupt the process and reset the clock. The most common way people lose the benefit is not a market crash, it is their own understandable urge to do something during one.' },
      { type: 'h', text: 'It works both ways' },
      { type: 'p', text: 'The same mechanism applies to costs and to debt. Fees compound against you over the years, and high-interest debt compounds against you just as relentlessly as returns compound for you. Understanding compounding is as much about respecting its downside as admiring its upside.' },
      { type: 'p', text: GENERAL_INFO },
    ],
  },
  {
    slug: 'active-passive-index-thinking',
    category: 'investment',
    title: 'Active, passive and the rise of index thinking',
    date: '2025-02-17',
    readingTime: '6 min read',
    summary:
      'The move toward low-cost index investing is one of the defining shifts of modern markets. Here is what changed and why it matters, as general commentary.',
    body: [
      { type: 'p', text: 'For most of investing history, the default was active management: a professional choosing holdings in the hope of beating the market. Over the last two decades, a quieter idea has reshaped the landscape: the notion that simply owning the whole market at low cost is hard to beat over the long run has moved from the fringe to the mainstream.' },
      { type: 'h', text: 'What the shift is really about' },
      { type: 'p', text: 'Index investing grew not because active management stopped trying, but because cost and consistency turned out to matter enormously over long periods. Fees and the breadth of holdings are known in advance, whereas future outperformance is not, and the published research on how often active funds beat their index over long periods is what drove the shift. That trade-off, rather than any single product, is the heart of the change.' },
      { type: 'h', text: 'The catch in the label' },
      { type: 'p', text: 'Passive does not mean safe, and index does not mean simple. An index fund still rises and falls with its market, and there are now thousands of indexes, some broad and cheap, others narrow, exotic and expensive dressed up in passive clothing. The word on the label tells you far less than what the fund actually holds and what it costs.' },
      { type: 'h', text: 'Not a religion' },
      { type: 'p', text: 'It would be a mistake to treat this as a settled war with a single winner. Both approaches have a place, and the right mix depends on goals, costs, tax, time horizon and temperament. The useful lesson from the rise of index thinking is not to pick a side, it is to take costs, diversification and your own behaviour seriously, whatever you ultimately choose.' },
      { type: 'p', text: GENERAL_INFO },
    ],
  },
  {
    slug: 'choosing-a-crm',
    category: 'business-tools',
    title: 'Choosing a CRM you will not regret in a year',
    date: '2025-01-16',
    readingTime: '5 min read',
    summary:
      'A CRM is one of the stickiest tools you will buy, so the wrong choice is costly to unwind. Pick for how you actually work, not for the longest feature list.',
    body: [
      { type: 'p', text: 'A customer relationship system quietly becomes the spine of a growing business, which is exactly why choosing badly hurts. Data, process and habits build up inside it, and moving to something else a year later is painful and disruptive. It pays to choose deliberately, even though the pressure is usually to just pick one and move on.' },
      { type: 'h', text: 'Buy for your process, not the demo' },
      { type: 'p', text: 'Every CRM demos beautifully, because the demo is designed to. The real question is whether it fits the way you actually win and keep clients. Map your real process first, from first enquiry to ongoing relationship, then judge tools against that specific flow. A shorter list of features you will use every day beats a long list of capabilities that look impressive and gather dust.' },
      { type: 'h', text: 'Adoption beats capability' },
      { type: 'p', text: 'The best CRM is the one your team will actually keep up to date. A powerful system nobody maintains is worse than a simple one everyone uses, because half-entered data is not just useless, it actively misleads. Favour something people find easy enough to live in every day, and involve the people who will use it in the choice.' },
      { type: 'h', text: 'Check the exits before you enter' },
      { type: 'p', text: 'Before you commit, find out how you would get your data out again, in a usable form, if you ever needed to leave. A tool that makes leaving hard is a tool that can raise prices or coast on quality with little you can do about it. Easy export is cheap insurance.' },
      { type: 'p', text: 'Start simpler than you think you need. You can grow into more capability, but you cannot easily recover the months lost to a tool that fought your team the whole way.' },
    ],
  },
  {
    slug: 'annual-marketing-rhythm',
    category: 'marketing',
    title: 'A simple annual marketing rhythm for busy owners',
    date: '2024-12-16',
    readingTime: '4 min read',
    summary:
      'Marketing fails less from bad ideas than from no rhythm. A light annual and monthly cadence keeps it going when the business gets busy, which is always.',
    body: [
      { type: 'p', text: 'For most owners, marketing does not fail because the ideas are poor. It fails because it is the first thing dropped when work gets busy, and then restarted from cold months later, having lost all its momentum. The cure is not more effort or more creativity, it is a rhythm that survives a hectic week.' },
      { type: 'h', text: 'Plan the year in an hour' },
      { type: 'p', text: 'Once a year, sketch the shape of the next twelve months: your busy and quiet seasons, a few themes you want to be known for, and any events, launches or moments worth building around. It does not need to be detailed or polished. It needs to exist, so that each month has a direction rather than a blank page and a sinking feeling.' },
      { type: 'h', text: 'Make the monthly commitment small' },
      { type: 'p', text: 'A modest amount done every month beats a burst once a quarter. One useful article, a handful of posts, one email to your list, kept up consistently, compounds in a way that sporadic brilliance never does. Consistency signals reliability, and reliability is much of what marketing is quietly selling on your behalf.' },
      { type: 'h', text: 'Repurpose rather than reinvent' },
      { type: 'p', text: 'You do not need a new idea every week. One good piece of thinking can become an article, several posts, an email and a talking point, each reaching people who missed the others. Treating one idea as raw material for the month removes most of the effort that makes owners give up.' },
      { type: 'p', text: 'Choose a cadence you can sustain on a bad month, not a good one. The plan that survives your busiest week is the one that actually works, and quietly beats every ambitious plan that was abandoned in week three.' },
    ],
  },
  {
    slug: 'where-ai-helps-small-business',
    category: 'ai',
    title: 'Where AI genuinely helps a small business today',
    date: '2024-11-15',
    readingTime: '5 min read',
    summary:
      'Beneath the hype, AI is already quietly useful for specific, everyday tasks. Knowing where it helps, and where it does not, is worth more than any prediction.',
    body: [
      { type: 'p', text: 'It is hard to think clearly about AI through the noise of hype and alarm. Set both aside and a practical picture emerges: for a small business, AI is already genuinely useful at a handful of everyday tasks, and unreliable at others. Knowing which is which is the whole game, and it changes slowly enough to be worth learning.' },
      { type: 'h', text: 'Where it earns its place' },
      { type: 'p', text: 'AI is strong at first drafts, at summarising long documents, at turning rough notes into something readable, at reformatting and tidying, and at answering how-do-I questions about software. These are tasks where a fast, imperfect starting point saves real time and a human still reviews the result before it matters. The pattern is: it does the eighty percent, you do the important twenty.' },
      { type: 'h', text: 'Where to be careful' },
      { type: 'p', text: 'It is weaker where accuracy is non-negotiable and cannot be easily checked, where specialised or very current knowledge is required, and anywhere a confident but wrong answer would cause real harm. In regulated work especially, AI drafts and people remain accountable. If you could not quickly tell whether the output is wrong, that is a task to approach with caution.' },
      { type: 'h', text: 'How to start without the risk' },
      { type: 'p', text: 'Pick one repetitive task, try AI on it for a fortnight alongside your normal way, and compare. Keep confidential data out of public tools, keep a human check on anything client-facing, and expand only where it clearly earns its place. Small, measured experiments beat both blanket bans and breathless roll-outs.' },
      { type: 'p', text: 'The businesses getting value from AI today are not chasing every headline. They have found two or three tasks where it reliably saves time, put a review step around it, and left the rest alone until it matures.' },
    ],
  },
  {
    slug: 'objection-handling-listening',
    category: 'sales',
    title: 'Objection handling is a listening skill, not a script',
    date: '2024-10-16',
    readingTime: '5 min read',
    summary:
      'Objections are not attacks to be defeated with clever lines. They are information. The best response is usually a better question, not a smoother rebuttal.',
    body: [
      { type: 'p', text: 'Much sales training treats objections as obstacles to be overcome with the right script. That framing sets up the conversation as a contest, and people can feel when they are being handled rather than heard. A better view is that an objection is information the client has kindly volunteered about what is standing between them and yes.' },
      { type: 'h', text: 'Understand before you answer' },
      { type: 'p', text: 'When someone says it is too expensive, that could mean several different things: it is genuinely beyond the budget, the value is not yet clear, the timing is wrong, or they need a reason to justify it to someone else. Answering the wrong version wastes the moment and can even create doubt that was not there. A calm question, such as can you tell me more about that, surfaces the real concern before you respond to the wrong one.' },
      { type: 'h', text: 'The most common objection is silence' },
      { type: 'p', text: 'Not every hesitation is spoken. Often the real objection is never voiced, and the prospect simply goes quiet and disappears. Making it safe to raise concerns, and gently asking what would need to be true for this to be an easy yes, brings the unspoken objection into the open where it can actually be addressed.' },
      { type: 'h', text: 'Some objections are the truth' },
      { type: 'p', text: 'Not every objection should be overcome. Sometimes the honest answer is that you are not the right fit, and saying so builds more trust than pushing ever could, and often earns a referral to someone you can help. A reputation for straight dealing wins more over time than a high close rate on the wrong clients.' },
      { type: 'p', text: 'Handle objections by listening first, understanding the real concern, and responding to that. It is slower than a script and far more persuasive, because it is not really a technique, it is genuine attention.' },
    ],
  },
  {
    slug: 'spotting-margin-leaks',
    category: 'analytics',
    title: 'Spotting margin leaks before they hurt',
    date: '2024-09-16',
    readingTime: '5 min read',
    summary:
      'Profit rarely disappears in one dramatic event. It leaks quietly, a little at a time, until a busy year somehow ends with less to show for it. Here is where to look.',
    body: [
      { type: 'p', text: 'Businesses rarely lose profit in a single dramatic stroke. They lose it slowly: a discount that became a habit, a service priced years ago and never revisited, a task that quietly takes twice as long as it is billed for. Individually invisible, together they explain the busy year that somehow ended with little to show for it.' },
      { type: 'h', text: 'Look at profit per thing, not just total' },
      { type: 'p', text: 'Total profit hides a great deal. Break it down by client, by service, by project or by product, and the leaks appear. Almost every business finds a segment it assumed was profitable that, once its true costs and the time it consumes are counted honestly, barely breaks even or quietly loses money while feeling busy and important.' },
      { type: 'h', text: 'Watch the slow drifts' },
      { type: 'p', text: 'The dangerous leaks are gradual: prices that never kept pace with rising costs, scope that crept without a change in fee, discounts offered once in a hard month and never withdrawn, and the small extra favours that add up to unpaid days. Because each change is tiny, none of them ever triggers an alarm, which is precisely why they need a deliberate, scheduled review.' },
      { type: 'h', text: 'Count the cost of your best clients too' },
      { type: 'p', text: 'A large client can be a hidden leak if they demand disproportionate time, endless revisions or slow payment. Revenue concentration also carries its own risk. It is worth knowing not just who pays you the most, but who is genuinely profitable once the true effort is included.' },
      { type: 'p', text: 'A simple quarterly look at profitability by segment catches most leaks while they are still small and easy to fix. The numbers are usually already in your systems, waiting to be asked the right question.' },
    ],
  },
  {
    slug: 'understanding-risk-volatility-vs-loss',
    category: 'education',
    title: 'Understanding risk: volatility is not the same as loss',
    date: '2024-08-15',
    readingTime: '5 min read',
    summary:
      'The word risk gets used loosely in finance, which leads to poor decisions. Separating short-term volatility from permanent loss is a foundational piece of financial literacy.',
    body: [
      { type: 'p', text: 'Risk is one of the most used and least examined words in finance. People reach for it to mean very different things, and the confusion leads to poor decisions. A useful first step in financial literacy is to separate two ideas that often get blurred together: volatility and permanent loss.' },
      { type: 'h', text: 'Volatility is movement, not disaster' },
      { type: 'p', text: 'Volatility is how much something bounces around in value along the way. It feels like risk, especially when values fall and the news is loud, but for a long-term investor it is often just noise. A holding can be volatile and still recover and grow over time. Reacting to volatility as though it were permanent loss, by selling into a fall, is a common and costly mistake that turns a temporary dip into a real, locked-in loss.' },
      { type: 'h', text: 'Permanent loss is the real concern' },
      { type: 'p', text: 'Permanent loss is capital you do not get back: a business that fails, a holding that never recovers, or selling in a panic and locking in a fall. The genuine risks worth managing carefully are the ones that do lasting damage, not the ones that merely feel uncomfortable for a few months and then pass.' },
      { type: 'h', text: 'The risk that fits your timeframe' },
      { type: 'p', text: 'Which risk matters most depends on when you need the money. For money you will spend next year, short-term swings are a real problem and stability matters. For money you will not touch for decades, short-term volatility matters far less than the slow erosion of inflation and fees. Matching the risk to the timeframe is more important than avoiding risk altogether.' },
      { type: 'p', text: GENERAL_INFO },
    ],
  },
  {
    slug: 'how-etfs-changed-investing',
    category: 'investment',
    title: 'How ETFs changed the way ordinary investors build portfolios',
    date: '2024-07-16',
    readingTime: '6 min read',
    summary:
      'Exchange-traded funds quietly rewired personal investing, making broad diversification cheap and simple. Here is what changed, offered as general commentary.',
    body: [
      { type: 'p', text: 'Few innovations have changed personal investing as much as the exchange-traded fund, and few are as easy to overlook. By packaging a whole basket of holdings into something you can buy in a single trade, on an ordinary exchange, at a low cost, ETFs made broad diversification cheap, simple and available to almost anyone.' },
      { type: 'h', text: 'Diversification made simple' },
      { type: 'p', text: 'Building a spread of holdings once took real capital, effort and cost, and was mostly out of reach for smaller investors. A single low-cost ETF can now provide exposure to hundreds or thousands of underlying holdings at once. For ordinary investors, that turned diversification from a project into a default, which is a genuinely meaningful shift in who gets to invest sensibly.' },
      { type: 'h', text: 'New tools, same principles' },
      { type: 'p', text: 'What ETFs did not change is the fundamentals. Diversification, cost, time horizon and temperament still decide outcomes. The wrapper is new; the rules of patient investing are not. It is easy to mistake a modern tool for a modern strategy, but the two are different things.' },
      { type: 'h', text: 'The label is not the product' },
      { type: 'p', text: 'The success of the ETF has also produced thousands of them, and they are not all alike. Some are broad and low-cost; others are narrow, leveraged, thematic or expensive, and behave nothing like the simple index funds that built the reputation. As always, what sits inside the product, and what it costs, matters far more than the three letters on the label.' },
      { type: 'p', text: GENERAL_INFO },
    ],
  },
  {
    slug: 'lean-tech-stack-services-business',
    category: 'business-tools',
    title: 'The lean tech stack for a services business',
    date: '2024-06-17',
    readingTime: '5 min read',
    summary:
      'It is easy to accumulate a dozen overlapping subscriptions and call it a system. A lean services business needs surprisingly few tools, chosen to work together.',
    body: [
      { type: 'p', text: 'Software is so easy to buy that many businesses end up with a drawer full of overlapping subscriptions, each solving part of a problem, none quite talking to the others. More tools is not more capability. Often it is just more cost, more logins, more training, and more places for information to hide from the people who need it.' },
      { type: 'h', text: 'The core a services business actually needs' },
      { type: 'p', text: 'Most service businesses run well on a small core: a way to manage clients and pipeline, a way to send and track invoices and get paid, a shared place for documents and knowledge, a scheduling tool, and reliable communication. Get those five working well and talking to each other before adding anything more specialised, however tempting the shiny option looks.' },
      { type: 'h', text: 'Integration over accumulation' },
      { type: 'p', text: 'The value is not in any single tool, it is in how they connect. Five tools that share information smoothly beat ten that each hold a separate, partial version of the truth and force people to copy data between them by hand. When evaluating anything new, the first question is not what it does, it is how it fits the tools you already rely on.' },
      { type: 'h', text: 'The hidden costs of a bloated stack' },
      { type: 'p', text: 'Every extra tool carries costs beyond its subscription: the time to learn it, the risk when the one person who understands it leaves, another place data can leak, and the quiet drag of context-switching between apps all day. A lean stack is not just cheaper, it is calmer and easier to run.' },
      { type: 'p', text: 'Review the stack once a year. Cancel what you stopped using, consolidate where you can, and resist buying a tool to solve a problem that a clear habit or a tidied process would fix for nothing.' },
    ],
  },
  {
    slug: 'positioning-clear-beats-clever',
    category: 'marketing',
    title: 'Positioning: why being clear beats being clever',
    date: '2024-05-16',
    readingTime: '5 min read',
    summary:
      'Most businesses describe themselves in ways that sound impressive and mean nothing. Clear positioning, who you help and how, does more work than any clever slogan.',
    body: [
      { type: 'p', text: 'Ask ten businesses what they do and most will answer in language that sounds professional and communicates almost nothing. Solutions, synergy, world-class, end-to-end, bespoke. The instinct to sound impressive quietly defeats the actual job of positioning, which is to be understood instantly and remembered later.' },
      { type: 'h', text: 'Clarity is the rare advantage' },
      { type: 'p', text: 'Because clever and vague is so common, clear and specific stands out. Who exactly do you help, what problem do you solve, and why you rather than the alternatives. A prospect who understands your positioning in one sentence can repeat it to someone else, which is how word of mouth actually travels. A clever line they cannot quite explain dies in the room it was said in.' },
      { type: 'h', text: 'Narrow to stand out' },
      { type: 'p', text: 'The fear is that being specific turns people away. In practice, trying to appeal to everyone is what makes you forgettable, because a message aimed at everyone lands on no one. A sharp position aimed at the clients you most want to win is more attractive to exactly those people, and being memorable to the right few beats being vaguely acceptable to all.' },
      { type: 'h', text: 'How to test it' },
      { type: 'p', text: 'A simple test: could a happy client describe what you do, accurately, to a friend, without you in the room. If not, the positioning is not clear enough yet, however elegant it sounds to you. Say it to a few real clients and listen to how they play it back; their version is often clearer than yours.' },
      { type: 'p', text: 'Good positioning is not a clever line. It is a clear, honest, specific answer to who this is for and why it matters, said the same way every time until the market believes it.' },
    ],
  },
  {
    slug: 'large-language-models-plain-terms',
    category: 'ai',
    title: 'Large language models, in plain business terms',
    date: '2024-04-16',
    readingTime: '5 min read',
    summary:
      'You do not need the technical detail to use these tools well, but a clear mental model helps you trust them where they are strong and check them where they are not.',
    body: [
      { type: 'p', text: 'The tools behind the recent wave of AI are called large language models, and the name is more helpful than it first appears. You do not need the mathematics to use them well, but a plain mental model helps you know when to trust the output and when to check it, which is most of the skill.' },
      { type: 'h', text: 'A very well-read pattern matcher' },
      { type: 'p', text: 'A useful way to picture one of these models is as something that has read an enormous amount of text and become extremely good at predicting what words should come next. That sounds modest, and yet at scale it produces writing, summaries and answers that are genuinely useful. It is closer to a fluent, well-read generalist than to a database of verified facts, and that distinction explains most of its quirks.' },
      { type: 'h', text: 'Why it is confident and sometimes wrong' },
      { type: 'p', text: 'Because the model predicts plausible language rather than looking up verified truth, it can state something incorrect with complete confidence, and even invent sources that look real. This is the single most important thing to understand. The fluency is real, but it is not the same as accuracy, which is why a human check matters wherever being wrong would cost you something.' },
      { type: 'h', text: 'What that means for how you use it' },
      { type: 'p', text: 'Give it context, because it cannot read your mind or see your files unless you show it. Lean on it for drafting, summarising and reshaping, where you can judge the result at a glance. Verify anything factual, especially names, numbers, dates and quotes. Used with that mental model, it becomes a fast, tireless assistant rather than an oracle to be trusted blindly.' },
      { type: 'p', text: 'Hold that picture in mind and these tools become far easier to use well: excellent for drafting and summarising, to be verified whenever facts matter.' },
    ],
  },
  {
    slug: 'sales-pipeline-that-predicts-revenue',
    category: 'sales',
    title: 'Building a sales pipeline that predicts revenue',
    date: '2024-03-16',
    readingTime: '5 min read',
    summary:
      'A pipeline is not a list of hopeful contacts. Done properly it is a forecast, and it tells you months ahead whether the quiet season you fear is actually coming.',
    body: [
      { type: 'p', text: 'Many businesses call their list of prospects a pipeline, but a list is not a pipeline. A real pipeline is a forecast: a structured view of future revenue that warns you, months in advance, whether the lean quarter you dread is actually on the way. That early warning is the entire point, because a gap you see coming is a problem you can still solve.' },
      { type: 'h', text: 'Define stages by the buyer, not by you' },
      { type: 'p', text: 'Useful stages describe where the client is in their decision, not how you feel about the deal. Enquiry, qualified, proposal sent, verbal agreement, closed. Clear definitions of exactly what has to be true to move a deal from one stage to the next keep the pipeline honest and stop wishful thinking from quietly inflating it into fiction.' },
      { type: 'h', text: 'A rough forecast beats none' },
      { type: 'p', text: 'Attach a rough value and a likelihood to each opportunity, based on its stage, and you can estimate what is genuinely coming. It will not be precise, and it does not need to be. Even an approximate forecast lets you act early, chasing more work before the gap arrives rather than scrambling after it has already hit the bank balance.' },
      { type: 'h', text: 'Watch flow, not just the total' },
      { type: 'p', text: 'A healthy pipeline is not a static pile, it is a flow: new opportunities entering, deals moving through, and stale ones being cleared out honestly. If nothing new is entering the top, a comfortable-looking total is a warning, not a comfort, because it will empty out in a few months with nothing behind it.' },
      { type: 'p', text: 'Keep it current and keep it honest. A pipeline you trust changes decisions and steadies your nerves. One you quietly know is inflated is just a list that makes you feel better while the real problem creeps closer.' },
    ],
  },
  {
    slug: 'five-numbers-to-watch-weekly',
    category: 'analytics',
    title: 'The five numbers every small business should watch weekly',
    date: '2024-02-15',
    readingTime: '5 min read',
    summary:
      'Annual accounts tell you what happened long after you could do anything about it. A handful of numbers watched weekly gives you time to act. Here is where to start.',
    body: [
      { type: 'p', text: 'Many owners only look closely at their numbers once a year, when the accounts arrive from the accountant. By then the story is history, and the moment to change it has long passed. A small set of numbers watched weekly turns your data from a post-mortem into an early warning system that still leaves time to act.' },
      { type: 'h', text: 'Start with cash' },
      { type: 'p', text: 'Cash in the bank, plus the cash you expect to come in and go out over the next few weeks, is the number that keeps businesses alive. Profitable businesses still fail when cash runs dry at the wrong moment, caught out by a big bill or a slow payer. Watching a simple rolling view weekly means you see a squeeze forming while you still have options, rather than discovering it on payday.' },
      { type: 'h', text: 'Then the leading indicators' },
      { type: 'p', text: 'Add new enquiries, because they predict future revenue before it appears. Add sales made or proposals accepted, because they confirm the pipeline is converting. Add overdue invoices, because unpaid work is cash you have already earned but not received. And add one measure specific to your business, whatever most closely tracks its health, such as utilisation, bookings, or units shipped.' },
      { type: 'h', text: 'Make it a ritual, not a project' },
      { type: 'p', text: 'The habit matters more than the tooling. A five-minute look at the same five numbers every Monday, ideally at the same time, builds an instinct for what normal looks like, so the abnormal jumps out at you. A fancy dashboard reviewed twice a year will never do that, however pretty it is.' },
      { type: 'p', text: 'Five numbers, a few minutes a week. Seen regularly, they give you the one thing annual accounts never can, which is time to act while acting still makes a difference.' },
    ],
  },
]
